### ISSUE TITLE
duda en nuevos campos 2.1

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-core#11]
Se agregó TotalImpuestos es requerido.
Se agregó MtoBaseIgv es requerido.
no estoy seguro del valor de estos campos:
TotalImpuestos = suma del igv de los productos por item ? 
MtoBaseIgv = ? (en el ejemplo veo que es igual al valor de venta) osea la suma del valor de los productos sin aplicar igv ?

**Comment by giansalex** [comment]
Hola @abelnexus, a nivel de detalle:
- **TotalImpuestos**, seria la suma de igv, isc, otros tributos.
- **MtoBaseIgv**, es el monto al cual aplicas el 18% y obtienes el igv, en el caso del ejemplo es el mismo que el ValorVenta, pero si hubiese ISC, seria `ValorVenta + ISC`

A nivel de cabecera, `TotalImpuestos`, es la suma del total Igv, isc, OtrosTributos

**Comment by abelnexus** [comment]
otra consulta amigo, las comunicaciones de baja y el resumen diario utilizan la versión 2.0 ?

**Comment by abelnexus** [comment]
en Greenter Changes hace referencia a que note requiere:
 TipoDeOperacion es requerido, ahora se toma del catálogo 51. pero cuando lo utilizo me indica que el método no esta definido

**Comment by abelnexus** [comment]
hola amigo no puedo solucionar este error:
Error: El producto del factor y monto base de la afectación del IGV/IVAP no corresponde al monto de afectacion de linea. - Detalle: xxx.xxx.xxx value='ticket: 1540047283675 error: Error en la linea: 1 Tributo: 1000: 3103 (nodo: "cac:TaxSubtotal/cbc:TaxAmount" valor: "4.27"

**Comment by giansalex** [comment]
En ese nodo, debes verificar que `TaxableAmount` multiplicado por `cac:TaxCategory/cbc:Percent` es igual a **4.27**
