### ISSUE TITLE
Como se calcula el campo porcentajeIgv?

### ISSUE THREAD

**Issue by carlosWilly** [giansalex/greenter-core#16]
porcentajeIgv

**Comment by carlosWilly** [comment]
El producto del factor y monto base de la afectación del IGV/IVAP no corresponde al monto de afectacion de linea. - Detalle: xxx.xxx.xxx value='ticket: 1562212744152 error: Error en la linea: 1 Tributo: 1000: 3103 (nodo: "cac:TaxSubtotal/cbc:TaxAmount" valor: "3.66")

**Comment by giansalex** [comment]
El campo `porcentajeIgv` no se calcula, representa el igv que aplica actualmente **18%**

**Comment by carlosWilly** [comment]
> Hola carlos, el campo `porcentajeIgv` no se calcula, representa el igv que aplica actualmente **18%**

pero cuando, coloco el impuesto me da el error:

El producto del factor y monto base de la afectación del IGV/IVAP no corresponde al monto de afectacion de linea. - Detalle: xxx.xxx.xxx value='ticket: 1562212744152 error: Error en la linea: 1 Tributo: 1000: 3103 (nodo: "cac:TaxSubtotal/cbc:TaxAmount" valor: "3.66")

**Comment by giansalex** [comment]
Y cual es el valor de `mtoBaseIgv`

**Comment by carlosWilly** [comment]
> Y cual es el valor de `mtoBaseIgv`

es 48

**Comment by carlosWilly** [comment]
es 24

**Comment by giansalex** [comment]
El producto seria `24*0.18=4.32`, y estas enviando `3.66` en el campo igv

**Comment by carlosWilly** [comment]
> El producto seria `24*0.18=4.32`, y estas enviando `3.66` en el campo igv

ok, voy revizarlo, gracias

**Comment by carlosWilly** [comment]
Podrias darme un ejemplo del valor que va en estos campos? a groso modo ..

"details": [
    {
      "unidad": "string",
      "cantidad": 0,
      "codProducto": "string",
      "codProdSunat": "string",
      "codProdGS1": "string",
      "descripcion": "string",
      "mtoValorUnitario": 0,
      "descuento": 0,
      "igv": 0,
      "tipAfeIgv": "string",
      "isc": 0,
      "tipSisIsc": "string",
      "totalImpuestos": 0,
      "mtoPrecioUnitario": 0,
      "mtoValorVenta": 0,
      "mtoValorGratuito": 0,
      "mtoBaseIgv": 0,
      "porcentajeIgv": 0,
      "mtoBaseIsc": 0,
      "porcentajeIsc": 0,
      "mtoBaseOth": 0,
      "porcentajeOth": 0,
      "otroTributo": 0,
}

**Comment by giansalex** [comment]
El mtoBaseIgv generalmente es el valor de venta, difieres cuando se incluye ISC. En general todos los que dicen mtoBase, es el valor que multiplicado por el porcentaje, resultara en el valor del igv, isc, etc. segun sea el caso.

**Comment by carlosWilly** [comment]
hay algun método para obtener el cdr?, viene en string

**Comment by giansalex** [comment]
ese contenido puedes guardarlo directamente con `file_put_contents('file-cdr.zip', $cdrString)`

**Comment by carlosWilly** [comment]
Una última, tengo este error al intentar generar el pdf, esoty usando  Lycet
